### ISSUE TITLE
link to user's profile

### ISSUE THREAD

**Issue by gosoccerboy5** [jeffalo/ocular#102]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when im on someones ocular page but I want to view they're scratch page, but theyres no direct link

**Describe the solution you'd like**
link to their scratch profile somewhere

**Describe alternatives you've considered**
idk

**Additional context**

https://github.com/jeffalo/ocular/blob/336644ed0a2e9b81243cd948d85e0f4621b7aea0/pages/user/_username.vue#L7

maybe you could change this to something like
```vue
 <h1 style="display: inline-block"><a href="https://scratch.mit.edu/users/{{ user }}">{{ user }}</a></h1> 
```
(I don't know vue sorry)

**Comment by FunctionalMetatable** [comment]
>  <h1 style="display: inline-block"><a href="https://scratch.mit.edu/users/{{ user }}">{{ user }}</a></h1>

would be
```vue
<h1 style="display: inline-block"><a :href="`https://scratch.mit.edu/users/${user}`">{{ user }}</a></h1>
```

**Comment by gosoccerboy5** [comment]
ok
