### ISSUE TITLE
show post counts

### ISSUE THREAD

**Issue by ajsya** [jeffalo/ocular#11]
Currently, it doesn't show post counts. It just says 0+ posts. I think this would be a handy thing to add. And you can obviously do it with the api.

_epic flashbacks to the wikipedia redirect glitch_

**Comment by JeffaloBob** [comment]
> _epic flashbacks to the wikipedia redirect glitch_

same

yes i think this would be good, but it's going to have to fetch lefty's api a lot more. I'll look into it

**Comment by jeffalo** [comment]
added in ocular 2.0
