### ISSUE TITLE
bolded emojis lose their colour

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/ocular#125]
google decided to go off spec or something, because in chrome 96, bolded emojis lose their colour.

![image](https://user-images.githubusercontent.com/40470736/142898378-011fa513-1ed3-4ed9-9b9e-d52aaf88448a.png)

([ocular isn't alone](https://user-images.githubusercontent.com/40470736/142898626-ab153f76-ec42-4d9e-b87e-018358061a75.png))

a solution is to wrap each bolded emoji with a span or something with a class that resets the font weight.

**Comment by JaydenDev** [comment]
Chrome has once again broke something! Hope it gets fixed soon, darn it Google!

**Comment by hello-smile6** [comment]
> google decided to go off spec or something, because in chrome 96, bolded emojis lose their colour.
> 
> ![image](https://user-images.githubusercontent.com/40470736/142898378-011fa513-1ed3-4ed9-9b9e-d52aaf88448a.png)
> 
> ([ocular isn't alone](https://user-images.githubusercontent.com/40470736/142898626-ab153f76-ec42-4d9e-b87e-018358061a75.png))
> 
> a solution is to wrap each bolded emoji with a span or something with a class that resets the font weight.

I have an idea! Why not just fix it? https://chromium.googlesource.com/
