### ISSUE TITLE
display OP badge

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/ocular#126]
show when a post is written by the OP

**Comment by micahlt** [comment]
Any preferred UI for this?

**Comment by jeffalo** [comment]
a microphone or a little badge that says "OP" with some description text would be nice, in the box alongside username and post count i suppose

**Comment by micahlt** [comment]
Gotcha - I'm taking this on.

**Comment by micahlt** [comment]
@jeffalo PR has been made and linked.
