### ISSUE TITLE
WHY IS THERE A RICKROLL IN A FORUM VIEWERRRR https://github.com/jeffalo/ocular/issues/73

### ISSUE THREAD

**Issue by hello-smile6** [jeffalo/ocular#129]
WHY IS THERE A RICKROLL IN A FORUM VIEWERRRR https://github.com/jeffalo/ocular/issues/73

_Originally posted by @Quantum-Codes in https://github.com/jeffalo/ocular/discussions/100_

I'll make a patch you can `git pull` to fix it

**Comment by Quantum-Codes** [comment]
discussion 100 is mine lol

**Comment by FunctionalMetatable** [comment]
no we need it, its a core part of ocular's functionality

**Comment by hello-smile6** [comment]
> no we need it, its a core part of ocular's functionality

Hmm... @jeffalo Could you put a poll on Ocular asking people to vote on this? If people think it's not necessary, could it be removed?

**Comment by Quantum-Codes** [comment]
> > no we need it, its a core part of ocular's functionality
> 
> Hmm... @jeffalo Could you put a poll on Ocular asking people to vote on this? If people think it's not necessary, could it be removed?

You could make a new issue/discussion for that

**Comment by hello-smile6** [comment]
Okay
