### ISSUE TITLE
stats

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/ocular#13]
stats will work kinda like shefwerld (catsunited) stats i guess.

i'm going to have to think about the layout and what libraries will be used. suggestions are obviously welcome!

**Comment by JeffaloBob** [comment]
#23 is WIP but its going good

**Comment by JeffaloBob** [comment]
ok its mostly done now i just need to do category stats

**Comment by YOYITsM3M8** [comment]
Hmmm

**Comment by YOYITsM3M8** [comment]
Instant reply

**Comment by mxmou** [comment]
You should probably close this now.
