### ISSUE TITLE
Can't search for "undefined"

### ISSUE THREAD

**Issue by mxmou** [jeffalo/ocular#130]
**Describe the bug**
Entering undefined into the search bar doesn't perform a search.

**To Reproduce**
1. Go to the search page
2. Type undefined into the search bar
3. Press "Enter" or click "go"

**Expected behavior**
It would show posts containing the word "undefined".

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 96

**Comment by jeffalo** [comment]
oops..

a workaround for now would be to do +content:"undefined"

**Comment by mxmou** [comment]
Fixed by [d8f89bb](https://github.com/jeffalo/ocular/commit/d8f89bbcb91325675cb2efae71c747425b738d3d)
![image](https://github.com/user-attachments/assets/a05e1dbc-503b-4dac-b891-2165403939c6)
