### ISSUE TITLE
Browse page text changes

### ISSUE THREAD

**Issue by Oren-Lindsey** [jeffalo/ocular#150]
**Describe the bug**
When you use the browse page the text changes when you click "go"
**To Reproduce**
1. Go to `/browse`, the browse page
2. Note the text. It says "note: this feature is in beta and **may be changed** at any time. **it's also** a bit slow due to scratchdb things."
3. Click "go"
4. The text changes to "note: this feature is in beta and **may change** at any time. **also it's** a bit slow due to scratchdb things."

**Expected behavior**
the text shouldn't change
**Screenshots**
Before:
<img width="862" alt="Screen Shot 2022-04-09 at 4 59 55 PM" src="https://user-images.githubusercontent.com/67929847/162591568-b91e218b-95a4-488d-ba13-0095a336cffb.png">

After:
<img width="807" alt="Screen Shot 2022-04-09 at 4 59 39 PM" src="https://user-images.githubusercontent.com/67929847/162591577-f65a2530-fb7a-4263-a2f2-a399eed4aaed.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: safari
 - Version: 15.4

**Additional context**
😛

**Comment by Oren-Lindsey** [comment]
aha found the problem. [browse/index.vue](https://github.com/jeffalo/ocular/blob/f691dac8de9f984342f57c6b2a926228a4ec3ddd/pages/browse/index.vue#L6) says one thing but [browse/_id.vue](https://github.com/jeffalo/ocular/blob/54e9c14eb572825e0379b4dfdc077bdad605d216/pages/browse/_id.vue#L6) says another

**Comment by jeffalo** [comment]
code duplication moment

**Comment by hello-smile6** [comment]
> code duplication moment

Use environment variables (Or require() a .json file) for anything that has text! Then you won't have that issue!
