### ISSUE TITLE
replace fluffyscratch with scratch auth

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/ocular#151]
works really well. might need to wait some time to see if there's any major flaws in it?

**Comment by Looky1173** [comment]
@jeffalo Thanks for considering Scratch Auth! If I were to discover some notable flaw with my system, I will let you know; although it looks like it's working reliably for now!

**Comment by ScolderCreations** [comment]
Isn’t this done?

**Comment by Looky1173** [comment]
> Isn’t this done?

My ocular still uses FluffyScratch API endpoints, although they redirect to Scratch Auth.

**Comment by jeffalo** [comment]
it would be faster if ocular used scratch auth directly (and also maybe more reliable), but for now this is resolved :)
