### ISSUE TITLE
Add links to user profiles to open profiles of users on other Scratch related sites

### ISSUE THREAD

**Issue by JaydenDev** [jeffalo/ocular#152]
**Is your feature request related to a problem? Please describe.**
Add more links to user profiles to open profiles of users on other Scratch related sites.
**Describe the solution you'd like**
Add more links to user profiles to open profiles of users on other Scratch related sites.

Basically more of these links:
![image](https://user-images.githubusercontent.com/92550746/163887491-7d39adef-7936-4348-8303-d298e1649409.png)

For sites like
https://scratchprofiler.vercel.app/ and https://jdev.eu.org/MyScratchPage (now supports url arguments so it'd work!)
and related sites

**Comment by jeffalo** [comment]
I can't really understand why this is necessary. Those websites seem to display the exact same data as eachother anyways.

**Comment by JaydenDev** [comment]
To be honest I entirely forgot about this issue post, it was literal months ago.
