### ISSUE TITLE
Press forward slash to set focus on search bar

### ISSUE THREAD

**Issue by DNin01** [jeffalo/ocular#158]
I noticed some websites (including GitHub and Bing) have this specific keyboard shortcut, and that's **`/` to search**. ocular is about searching, so a little enhancement to make searching ever so slightly faster might be cool.
1. If you need to change your search terms right after you search, you won't have to lift your fingers off the keyboard (your fingers will probably be over the keyboard already)
2. You'll never need to spend time moving the mouse pointer up to the search bar
3. This would help keyboard-only users save even more time

**Comment by jeffalo** [comment]
done in [ocular-rewritten](https://ocular-rewritten.jeffalo.net/)! d3693265bcb24bbffe3a632869b7e8ff4b0592df

**Comment by DNin01** [comment]
Nice! I've also seen that `s` is another shortcut key for jumping to the search bar, so maybe you could add that option, too?

**Comment by jeffalo** [comment]
i haven't seen s much.. which sites use s?

**Comment by DNin01** [comment]
> i haven't seen s much.. which sites use s?
> 
> (edit: i accidently closed the issue, ignore that)

GitHub's secondary search key is S, and Bing switched to using S.

**Comment by RedGuy12** [comment]
Google uses / tho


________________________________

**Comment by DNin01** [comment]
Alright, we have `/` to search. Feel free to add `s` to search later, but I think this issue is, for the most part, done.
