### ISSUE TITLE
Change credit for auth api to Looky1173

### ISSUE THREAD

**Issue by LegoManiac04** [jeffalo/ocular#162]
The [footer](https://github.com/jeffalo/ocular/blob/main/components/Footer.vue#L11) credits the authentication api to herohamp, however since the auth api was switched over to Scratch Auth, it should instead credit Looky1173.

I'm unsure if the link should link to their Scratch profile, or to Scratch Auth itself, and I was unsure if I could just PR this right off the bat, so I thought I'd just make an Issue.

**Comment by Weredime** [comment]
make a pr then
