### ISSUE TITLE
Replace FluffyScratch with Scratch Auth in docs

### ISSUE THREAD

**Issue by Adzboy** [jeffalo/ocular#164]
[This page](https://ocular.jeffalo.net/docs/privacy) should be changed to say Scratch Auth not FluffyScratch.

`Scratch based authentication is handled by FluffyScratch.`
Should be
`Scratch based authentication is handled by Scratch Auth`
with a link to https://auth.itinerary.eu.org/

**Comment by jeffalo** [comment]
thanks!

**Comment by Adzboy** [comment]
Made a pull request for this (#165). Pretty easy to sort outt.
