### ISSUE TITLE
It looks like a backslash was accidentally left in the search filters table

### ISSUE THREAD

**Issue by DNin01** [jeffalo/ocular#174]
**Describe the bug**
Typo here:
https://github.com/jeffalo/ocular/blob/6391994547587a9ad35b78501e2c34c6f58bdfc7/pages/search.vue#L104

**To Reproduce**
Go to ocular's [search page](https://ocular.jeffalo.net/search).

**Screenshots**
![A picture of ocular's table of search filters](https://user-images.githubusercontent.com/106490990/199636499-c3f17238-7c33-4003-a76c-c90cb1f1bfa6.png)

**Desktop (please complete the following information):**
Not applicable

**Smartphone (please complete the following information):**
Not applicable

**Comment by jeffalo** [comment]
oops!
