### ISSUE TITLE
Please stop using ScratchDB

### ISSUE THREAD

**Issue by GenericProgrammer1234** [jeffalo/ocular#187]
As we have seen because it's a website it frequently goes down every few days or such, however libraries like Meowclient cannot which will provide a better user experience.

**Pros:**
- Improved UX
- MeowClient gets more recognition

**Cons:**
- Huge technical changes

(I was almost gonna have a heart attack seeing that Vue has a separate syntax highlighting on GitHub lol)
(finally my quest for fame will be answered)

**Comment by RedGuy12** [comment]
....that would mean ocular would have to fetch EVERY single post on scratch for things such as searching. do you know how much _lag_ that would be? it would not be pretty. whatever account it uses to fetch the data would probably be banned from scratch pretty quickly (meowclient shouldn't require auth tho, you don't need it to fetch?)

scratchdb is a database, it's in the name (db=database). any service like a database or API or website will have inevitable downtime, it's just to be expected. but scratchdb doesn't even go down that much and when it's reported to mozzy it's fixed quite quickly in my experience

**Comment by GenericProgrammer1234** [comment]
Any activity?

**Comment by jeffalo** [comment]
ocular is primarily a search engine. more than that, it's a scratchdb frontend. i'm not sure what value it would have as a dedicated tool for "viewing topics" directly from scratch.
