### ISSUE TITLE
Add Forum 45 to category-map

### ISSUE THREAD

**Issue by 7salad3salad** [jeffalo/ocular#190]
**Describe the bug**
Forum 45 is missing from this list: https://github.com/jeffalo/ocular/blob/main/assets/category-map.js

**To Reproduce**
1. Go to the list
2. Scroll to where it would be
3. It is not there

**Expected behavior**
I expected it to be there

**Additional context**
Forum 45 leads to 404, but seing as 43 and 47 are there i think it should be there too.

**Comment by jeffalo** [comment]
done! thanks
