### ISSUE TITLE
cleaner messes up with <a> tags

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/ocular#29]
the cleaner which is meant to prevent xss, messes up if a post contains <a> in the content, and turns the rest of the post into a link i have no clue why this happening.

**Comment by JeffaloBob** [comment]
here is the cleaner, but it's probably an issue with how posts are rendered.
https://github.com/JeffaloBob/ocular/blob/main/search.html#L339

**Comment by JeffaloBob** [comment]
example post https://ocular.jeffalo.net/search?post=4492318
scratchdb https://scratchdb.lefty.one/v2/forum/post/4492318

i noticed that scratchdb puts the <a> like that so the cleaner might need to handle unclosed a tags and stuff ¯\\\_(ツ)\_/¯

**Comment by JeffaloBob** [comment]
i committed 57af2bfb4abccf31fc2a3cab3a2df0ef0d1bc468 which might fix this, but since scratchindexer is behind i can't test if the same thing happens with <b> and <i> etc

**Comment by jeffalo** [comment]
fixed by lefty
