### ISSUE TITLE
Markdown or BBCode for statuses

### ISSUE THREAD

**Issue by SausageMcSauce** [jeffalo/ocular#30]
My former Shef Werld Post Viewer status contained HTML in it. HTML is not supported in statuses currently, so I think there should be a way to add formatting for statuses.

HTML probably should not be implemented instead of what is mentioned in the title, because of XSS, obviously.

**Comment by JeffaloBob** [comment]
thanks for the suggestion!
markdown would be interesting, i might go with bbcode to be forumy, but i'll need to find a good bbcode parser.

**Comment by JeffaloBob** [comment]
also i'll have to talk with catsunited because this would have to be done client side

**Comment by jeffalo** [comment]
i dont think this is something i intend on supporting
