### ISSUE TITLE
question: where is the my-ocular source code?

### ISSUE THREAD

**Issue by FunctionalMetatable** [jeffalo/ocular#34]
just want to see how its built

**Comment by jeffalo** [comment]
closed source currently, built with mongodb, nodejs, express and ejs

**Comment by FunctionalMetatable** [comment]
> closed source currently, built with mongodb, nodejs, express and ejs
`[
ok: thank you for the reply;
]`
Why did I put that in code format

**Comment by jeffalo** [comment]
in case anyone is reading this later, its now open source at https://github.com/jeffalo/my-ocular
