### ISSUE TITLE
Statuses can get too large in length and make Forums lag with SA on

### ISSUE THREAD

**Issue by FunctionalMetatable** [jeffalo/ocular#35]
**Describe the bug**
Statuses can become very large when setting them with my ocular.

**To Reproduce**
1. Keep copying a random piece of text for some time
2. Set it to your ocular status
3. It lets you keep it, its annoying when its on [CENSORED].

**Expected behavior**
A max character limit of 100-200

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Edge

Sorry if I caused lag to your server, I was just testing.

**Comment by jeffalo** [comment]
i am too trusting

**Comment by FunctionalMetatable** [comment]
> i am too trusting

srry still i was just testing

**Comment by RedGuy12** [comment]
@jeffalo why censored?

**Comment by retronbv** [comment]
> @jeffalo why censored?

It named that browser extension and I don't think jeffalo wants that name mentioned on here

**Comment by jeffalo** [comment]
this was fixed i believe
