### ISSUE TITLE
Links to the Scratch Youtube video player on posts when viewed on ocular go to a nonexistent page of ocular

### ISSUE THREAD

**Issue by SausageMcSauce** [jeffalo/ocular#37]
**Describe the bug**
When there is a link to the Scratch YouTube player on a post viewed on ocular, the link goes to a nonexistent page (https://ocular.jeffalo.net/discuss/youtube/ _whatever goes here_ ). I think this happens due to the way the Scratch Forum's internals link to it. 

**To Reproduce**
1. View any page that has a link to Youtube that goes to Scratch's Youtube player
2. Click on the link
3. Clicking it gives a 404 error, hovering over it shows a link to the nonexistent spage.

**Expected behavior**
The link goes to Scratch's Youtube Player. 

One way of solving this is by ocular making its own Youtube player or redirecting the nonexistent subpage to Scratch's player.

**Screenshots**

An example of the bug is [here](https://ocular.jeffalo.net/post/4917795) .

**Desktop (please complete the following information):**

Likely happens in all browsers, but I use Chrome 88 on Windows 10.

**Additional context**

**Comment by jeffalo** [comment]
sorry for missing this, i will add an ocular youtube page

**Comment by jeffalo** [comment]
added
