### ISSUE TITLE
name/brand

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/ocular#4]
furthering the name/brand through creating a logo/better name.

ideas are welcome!

**Comment by JeffaloBob** [comment]
this extends to some kind of favicon. for now im going to use the 🔎 or 🔍 emoji.

**Comment by Nagol12344** [comment]
Does something like this work
![image](https://user-images.githubusercontent.com/63481547/100756530-45548500-33bb-11eb-93e3-1b72a973b449.png)

**Comment by jeffalo** [comment]
i think the green and magnifying glass svg/emoji seem to have become the brand now

**Comment by Chaos-emerald** [comment]
Working on one.

**Comment by jeffalo** [comment]
i appreciate the enthusiasm, however i think im fine with the current logo.
