### ISSUE TITLE
Add link to the post to ocular.jeffalo.net/react

### ISSUE THREAD

**Issue by mxmou** [jeffalo/ocular#50]
**Is your feature request related to a problem? Please describe.**
The popup that opens when reacting to a post using ScratchAddons/ScratchAddons#2163 only contains the ID of the post, which isn't very helpful. It also makes tricking people to react to posts easier.

**Describe the solution you'd like**
Use a link or a preview of the post instead.

**Comment by RedGuy12** [comment]
Probably should go in https://github.com/jeffalo/ocular
________________________________
From: Maximouse ***@***.***>
Sent: Sunday, April 18, 2021 12:40:41 PM
To: jeffalo/ocular ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffalo/ocular] Add link to the post to ocular.jeffalo.net/react (#50)


Is your feature request related to a problem? Please describe.
The popup that opens when reacting to a post using ScratchAddons/ScratchAddons#2163<https://github.com/ScratchAddons/ScratchAddons/pull/2163> only contains the ID of the post, which isn't very helpful. It also makes tricking people to react to posts easier.

Describe the solution you'd like
Use a link or a preview of the post instead.

**Comment by mxmou** [comment]
@RedGuy12 This *is* jeffalo/ocular, isn't it?

**Comment by RedGuy12** [comment]
Oh I missread it as https://github.com/scratchaddons/scratchaddons whoops
________________________________

**Comment by jeffalo** [comment]
how about "are you sure you want to react to jeffalo's post" where "jeffalo's post" links to the post on scratch?

this will require an extra request though.

**Comment by mxmou** [comment]
> how about "are you sure you want to react to jeffalo's post" where "jeffalo's post" links to the post on scratch?
> 
> this will require an extra request though.

If the extra request is not a problem, this is probably the best option.

**Comment by jeffalo** [comment]
the big issue is supporting scratch addons. because scratchindexer doesn't have all posts instantly, SA users will not be able to react to brand new posts.

perhaps i will need a my-ocular api endpoint for poster username? or maybe if scratchdb doesn't return a poster username just use "this post" instead of "jeffalo's post"

this will be tricky to get right.

**Comment by jeffalo** [comment]
solved in 796d3dbb6e829ebf0597d452421f771cfead2fe6 it was not actually very tricky

**Comment by RedGuy12** [comment]
Hmm... you could webscrape it yourself, but I know from experience that it's not that fast. You could fetch the post content from https://scratch.mit.edu/discuss/post/ID/source which is a bit faster, but doesn't give as much context as ScratchDB would.
________________________________

**Comment by jeffalo** [comment]
reopening because i forgot to actually make a link.
