### ISSUE TITLE
Error message when ScratchDB is down

### ISSUE THREAD

**Issue by mxmou** [jeffalo/ocular#51]
**Is your feature request related to a problem? Please describe.**
ScratchDB sometimes has problems. When this happens, Ocular displays no results but doesn't show an error message.

**Describe the solution you'd like**
An error message.

**Comment by Quantum-Codes** [comment]
Make a request timeout = 30s ?

**Comment by retronbv** [comment]
> Make a request timeout = 30s ? 

Maybe people have really slow internet

**Comment by Quantum-Codes** [comment]
> > Make a request timeout = 30s ?
> 
> Maybe people have really slow internet

No. ScratchDB is slow even I you have alien WiFi.

**Comment by Turtle84375** [comment]
I don't really code in Vue, but if you could get the HTTP code returned from the GET request to ScratchDB, it shouldn't be difficult to check it as the results render in and display an error message instead if the request returns 500 or something like that.

(I probably don't know what I'm talking about, don't mind me if I sound completely stupid.)

**Comment by micahlt** [comment]
Shouldn't be hard to do - I'll work on this!  Do we have any guidelines for what the error should look like?

**Comment by micahlt** [comment]
#154 will resolve this issue.
