### ISSUE TITLE
Add back missing-glasses, as well as add dark-glasses

### ISSUE THREAD

**Issue by Chaos-emerald** [jeffalo/ocular#52]
Bringing back the missing-glasses theme would be awesome! As well as dark-glasses, just dark mode and missing-glasses

**Comment by Chaos-emerald** [comment]
Bump, but don't block me.

**Comment by Looky1173** [comment]
I've heard that the missing-glasses theme was for April Fools. It might be readded next year!

**Comment by retronbv** [comment]
> Bump, but don't block me.

You don't need to bump posts, this is not the scratch forums. If jeffalo doesn't respond that means he hasn't had time to open GitHub or doesn't feel like working on this.

**Comment by jeffalo** [comment]
missing glasses was an april fools theme. maintaining it is not very productive since no one actually uses it.
