### ISSUE TITLE
Could you change my status?

### ISSUE THREAD

**Issue by Chaos-emerald** [jeffalo/ocular#58]
I'm Ilikesonic100 on Scratch, change my status to "permanently banned by scratch cat" because I got blocked permanently because they think I'm abusing the forums, and when I moved to CodeEmerald, they blocked my IP address.

**Comment by FunctionalMetatable** [comment]
you still should be logged in still as the token should persist between sessions

**Comment by Chaos-emerald** [comment]
@FunctionalMetatable I cleared my cookies, so I'm not logged in

**Comment by jeffalo** [comment]
sorry. banned users on scratch are also "banned" on ocular. i wish i could help you but then i'd be breaking the scratch community guidelines.

**Comment by Emerald-chaos** [comment]
> i wish i could help you but then i'd be breaking the scratch community guidelines

No you would not be breaking them.
