### ISSUE TITLE
/post/:id/embed

### ISSUE THREAD

**Issue by FunctionalMetatable** [jeffalo/ocular#60]
Please add an embeddable post viewer to ocular, like this
![image](https://user-images.githubusercontent.com/67440879/116792176-f8362580-aab6-11eb-8b02-28fcd06413fb.png)
but just as-is and iframeable

**Comment by jeffalo** [comment]
i'm trying to figure out if i can get the query parameters in the force colour mode options
https://color-mode.nuxtjs.org/#force-a-color-mode

then it would be possible to choose a theme that matches the site that ocular is being embedded on.

if i can't figure it out, i think it'll just be the default light and green theme.

**Comment by jeffalo** [comment]
done
