### ISSUE TITLE
signature history?

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/ocular#64]
9gr's https://signature-history.9gr.repl.co/?user=Jeffalo works really well and its pretty useful. is this something i should implmenet in ocular? i do not want to copy their website since they do a good job with it already.

**Comment by FunctionalMetatable** [comment]
do it

**Comment by jeffalo** [comment]
ok

**Comment by jeffalo** [comment]
i dont think ocular should show signature history... there are privacy concerns with that.
