### ISSUE TITLE
scratchblocks don't function in singular post view

### ISSUE THREAD

**Issue by vivilua** [jeffalo/ocular#65]
when viewing a list of posts, the scratchblocks function the same as on the forums.
however, when you go to the singular post view, the scratchblocks aren't formatted correctly and turn red.

**to reproduce**
1. go to a user's ocular profile, a topic, or the search results
2. click on the post date in the upper left to go the singular post viewer

**desktop**
- os: windows 10
- browser: chrome 88 (works on edge 90 as well)

(also noticed that the ". . ." booleans don't automatically turn gray on ocular, unlike regular scratch)

![image](https://user-images.githubusercontent.com/81496469/117412242-6882e380-aec9-11eb-8d8e-9af5826f32ce.png)
![image](https://user-images.githubusercontent.com/81496469/117412306-7e90a400-aec9-11eb-9653-48d8d3445c5d.png)

**Comment by jeffalo** [comment]
thanks. i'll look into this.

> (also noticed that the ". . ." booleans don't automatically turn gray on ocular, unlike regular scratch)

is this an issue with ocular or with scratchblocks? im not sure.

**Comment by jeffalo** [comment]
fixed! was some legacy code i forgot to remove
