### ISSUE TITLE
Remove my-ocular from templates

### ISSUE THREAD

**Issue by Shluffy** [jeffalo/ocular#66]
**Is your feature request related to a problem? Please describe.**
my-ocular isn't really a thing anymore
**Describe the solution you'd like**
to not say my-ocular

**Describe alternatives you've considered**
remove my-ocular from templates
**Additional context**
![image](https://user-images.githubusercontent.com/81823039/117687784-20441980-b186-11eb-9c95-077b990662e2.png)

**Comment by FunctionalMetatable** [comment]
instead there should be that kind of templates in the actual [my-ocular repo](https://github.com/jeffalo/my-ocular)
