### ISSUE TITLE
Typo with link

### ISSUE THREAD

**Issue by gosoccerboy5** [jeffalo/ocular#67]
**Describe the bug**

**To Reproduce**
1. Go to https://ocular.jeffalo.net/docs/gallery
2. Click on [edit this page](https://github.com/jeffalo/ocular/blob/main/content/gallery.md)
<s>3. Scroll down to '....'</s>
4. See error _without_ having to scroll down

**Expected behavior**
The link should work, and lead to [content/docs/gallery.md](https://github.com/jeffalo/ocular/blob/main/content/docs/gallery.md)

**Screenshots**
Wow, you're pushy. It's just a 404 page. alright, fine
<img width="300" alt="Screen Shot 2021-05-13 at 3 06 46 PM" src="https://user-images.githubusercontent.com/82768218/118181033-e3ce2300-b3fc-11eb-8f91-3fe084594da6.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 2020
 - Browser: Firefox
 - Version 88.0

**Additional context**
None, other than the fact that I like links to work

**Comment by gosoccerboy5** [comment]
Lol, you add a label but don't fix it :P

**Comment by jeffalo** [comment]
> Lol, you add a label but don't fix it :P

why of course.. that would take too long!

**Comment by gosoccerboy5** [comment]
I feel u
