### ISSUE TITLE
Clicking category on topic page should link back to that category (on Ocular)

### ISSUE THREAD

**Issue by towerofnix** [jeffalo/ocular#75]
**Is your feature request related to a problem? Please describe.**

I might be something but I don't *think* there's a way to get back to the forum category / subforum once you click a topic, besides using the browser's own back button? :P

**Describe the solution you'd like**

Clicking the category name above the first post on a topic page should bring you to that category's browse page!

**Describe alternatives you've considered**

Another option would be to overhaul the nav bar to show the forum name, e.g. "ocular / advanced topics / topic", but that miiiight look a bit odd and not fit super well with the current UI. But it's an option! :shipit:

**Additional context**

The Browse index still describes itself as in beta, so highlighting it super extensively might not be a priority. I think making the small-font category text clickable is useful and non-obtrusive enough to be fine, even with that in mind, though.

**Comment by jeffalo** [comment]
thanks. this is a good idea.
