### ISSUE TITLE
Add Login Button on Homepage

### ISSUE THREAD

**Issue by linearlemur** [jeffalo/ocular#97]
**Is your feature request related to a problem? Please describe.**
There is no button on the homepage leading to the login page

**Describe the solution you'd like**
Add a button on the homepage leading to the login page

**Comment by FunctionalMetatable** [comment]
> **Is your feature request related to a problem? Please describe.**
> There is no button on the homepage leading to the login page
> 
> **Describe the solution you'd like**
> Add a button on the homepage leading to the login page

The dashboard button?

**Comment by linearlemur** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > There is no button on the homepage leading to the login page
> > **Describe the solution you'd like**
> > Add a button on the homepage leading to the login page
> 
> The dashboard button?

Oh right.
